### ISSUE TITLE
patched bussy

### ISSUE THREAD

**Issue by Cha14ka** [snoobi-seggs/nilou_seggs#1]
hello comrade, where cat I grab cyno`s patched metadata bussy?

**Comment by wonkus2** [comment]
> hello comrade, where cat I grab cyno`s patched metadata bussy?

no

**Comment by Julienraptor01** [comment]
I was able to get patched Metadata/UserAssembly.dll (both method work) for 3.0.50 but i updated to 3.0.51 but i forgor to try to find Patched Metadata/UA first because i'm a retard.
I noticed you put some metadata in [3.0FORretards](https://github.com/snoobi-seggs/3.0FORretards/tree/master/METADATA%20FOR%20PATCHING) but it's for regular 3.0.
Can you resolve my skill issue pls ?

Edit : i got patched CN UA from somewhere and it seem to work fine on OS... Seems like MHY is having fun

**Comment by snoobi-seggs** [comment]
> I was able to get patched Metadata/UserAssembly.dll (both method work) for 3.0.50 but i updated to 3.0.51 but i forgor to try to find Patched Metadata/UA first because i'm a retard. I noticed you put some metadata in [3.0FORretards](https://github.com/snoobi-seggs/3.0FORretards/tree/master/METADATA%20FOR%20PATCHING) but it's for regular 3.0. Can you resolve my skill issue pls ?
> 
> Edit : i got patched CN UA from somewhere and it seem to work fine on OS... Seems like MHY is having fun

bruh dont stalk my github like some Instagram acc>:( jk anyways by now u confm alr found it so as a responsible person i shall close this issue heh _snoo_
